# URL to request form to claim exclusive Hack Club stickers
claim-stickers-url: "https://example.com/claim-stickers"
settings:
  # Time in seconds after which a player will be automatically set to AFK
  auto-afk-time: 600
  # Time in seconds between requests are made to the Shrimp Shuffler API to change the server icon.
  icon-change-time: 600
  spawn-command:
    # Radius extending from the world spawn in which the command can be used
    allowed-radius: 2000
    # Time in seconds a player has to wait before being able to use the command again
    damage-cooldown: 10
  slack-link:
    # Whether the Slack integration is enabled
    enabled: false
    # Whether to require a Slack link to join the server
    required: false
    # Time in seconds after which the code will expire
    link-code-expiration: 600
    # The Slack bot token
    bot-token: ""
    # The Slack app token
    app-token: ""
    # The Slack channel ID to send Minecraft messages to and from
    channel-id: ""
    # The base Slack command
    base-command: "minecraft"
